apiVersion: v1
kind: ConfigMap
metadata:
  name: canary
data:
  index-canary.html: "<!DOCTYPE html>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html;
    charset=utf-8\" />\r\n<html>\r\n    <head><font color=\"yellow\">canary</head>\r\n"
