apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-main
data:
  index-main.html: "<!DOCTYPE html>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html;
    charset=utf-8\" />\r\n<html>\r\n    <head><font color=\"red\">main</head>\r\n"
